/* ============================================================
   EDGE — teach.js
   The teaching engine: WHY a hand plays the way it does,
   border-hand analysis, and EV-style mistake severity.

   PREFLOP_RANK was generated by Monte-Carlo equity vs a random
   hand (12k sims per class) — see test-teach.js for validation.
   ============================================================ */
'use strict';

var PREFLOP_RANK = ["AA","KK","QQ","JJ","TT","99","88","AKs","77","AQs","AJs","AKo","AQo","ATs","KQs","66","AJo","A9s","ATo","KJs","KQo","KTs","A8s","A9o","A7s","KJo","A6s","55","KTo","A5s","A8o","K9s","QJs","QTs","A4s","A7o","K8s","JTs","A3s","K9o","QJo","A6o","A2s","QTo","K6s","Q9s","A5o","K7s","Q9o","K5s","A4o","44","Q8s","K8o","JTo","J9s","A3o","K4s","A2o","K7o","K6o","J8s","K3s","Q8o","Q7s","K5o","33","K4o","J9o","Q6s","T9s","K2s","T9o","Q5s","J7s","Q7o","K3o","Q6o","T8s","J8o","K2o","Q4s","98s","J5s","T7s","Q5o","Q2s","Q3s","J6s","J7o","22","T8o","Q4o","97s","J4s","T6s","98o","T7o","J6o","96s","Q2o","J3s","87s","T5s","Q3o","J5o","J2s","86s","J4o","T4s","95s","T3s","96o","97o","T6o","J2o","J3o","85s","76s","T2s","87o","94s","T5o","86o","T4o","95o","75s","93s","65s","84s","T3o","85o","92s","74s","76o","T2o","64s","83s","54s","94o","53s","75o","82s","93o","65o","73s","92o","84o","63s","72s","74o","62s","52s","43s","64o","54o","42s","83o","53o","82o","63o","73o","32s","43o","52o","72o","62o","42o","32o"];

var RANK_INDEX = {};
(function () { for (var i = 0; i < PREFLOP_RANK.length; i++) RANK_INDEX[PREFLOP_RANK[i]] = i; })();
function handRank(label) { return RANK_INDEX[label]; } // 0 = best of 169

/* ---------- hand families (for border analysis) ----------
   Pairs are one family; non-pairs grouped by high card + suitedness. */
function familyOf(label) {
  if (label.length === 2) return 'pairs';
  return label[0] + label[2]; // e.g. "As", "Ko", "Ts"
}
var FAMILY_NAMES = {
  pairs: 'pairs', As: 'suited aces', Ao: 'offsuit aces', Ks: 'suited kings',
  Ko: 'offsuit kings', Qs: 'suited queens', Qo: 'offsuit queens', Js: 'suited jacks',
  Jo: 'offsuit jacks', Ts: 'suited tens', To: 'offsuit tens', '9s': 'suited 9x',
  '9o': 'offsuit 9x', '8s': 'suited 8x', '8o': 'offsuit 8x', '7s': 'suited 7x',
  '7o': 'offsuit 7x', '6s': 'suited 6x', '6o': 'offsuit 6x', '5s': 'suited 5x',
  '5o': 'offsuit 5x', '4s': 'suited 4x', '4o': 'offsuit 4x', '3s': 'suited 3x', '3o': 'offsuit 3x'
};
/* second-card height used to order inside a family (pairs: pair rank) */
function familyStep(label) {
  if (label.length === 2) return RANKS.indexOf(label[0]);
  return RANKS.indexOf(label[1]);
}

/* ---------- per-chart border map ----------
   For each family with members in the chart: contiguous in-chart segments
   (by second card descending), e.g. suited aces -> "ATs+, A5s-A2s".
   bordersFor(chartId) -> [{family, segments:[{hi,lo}], borderLabel}] */
var _borderCache = {};
function bordersFor(chartId) {
  if (_borderCache[chartId]) return _borderCache[chartId];
  var compiled = COMPILED_CHARTS[chartId];
  var fams = {};
  for (var label in compiled.chart) {
    var f = familyOf(label);
    (fams[f] = fams[f] || []).push(label);
  }
  var out = [];
  for (var fam in fams) {
    var present = {};
    fams[fam].forEach(function (l) { present[familyStep(l)] = l; });
    // walk from high step down, building segments
    var segs = [], cur = null;
    for (var step = 12; step >= 0; step--) {
      var l2 = present[step];
      if (l2) {
        if (!cur) cur = { hi: l2, lo: l2 };
        else cur.lo = l2;
      } else if (cur) { segs.push(cur); cur = null; }
    }
    if (cur) segs.push(cur);
    if (!segs.length) continue;
    var lowest = segs[segs.length - 1].lo;
    out.push({ family: fam, name: FAMILY_NAMES[fam] || fam, segments: segs, border: lowest });
  }
  // stable, readable order
  var famOrder = ['pairs', 'As', 'Ao', 'Ks', 'Ko', 'Qs', 'Qo', 'Js', 'Jo', 'Ts', 'To', '9s', '9o', '8s', '8o', '7s', '7o', '6s', '6o', '5s', '5o', '4s', '4o'];
  out.sort(function (a, b) { return famOrder.indexOf(a.family) - famOrder.indexOf(b.family); });
  _borderCache[chartId] = out;
  return out;
}
function segText(seg) {
  if (seg.hi === seg.lo) return seg.hi;
  // pairs: "TT-77", others "ATs-A7s" -> compact "+": if hi is family's top possible, keep dash form (clear enough)
  return seg.hi + '-' + seg.lo;
}
function borderSummary(chartId) {
  return bordersFor(chartId).map(function (b) {
    return { name: b.name, text: b.segments.map(segText).join(', '), border: b.border };
  });
}

/* distance (in family steps) from a label to its family's nearest in-chart
   segment edge. 0 = it IS a border hand. Positive = outside, negative = inside. */
function borderDistance(chartId, label) {
  var compiled = COMPILED_CHARTS[chartId];
  var fam = familyOf(label);
  var info = null;
  var bs = bordersFor(chartId);
  for (var i = 0; i < bs.length; i++) if (bs[i].family === fam) info = bs[i];
  var step = familyStep(label);
  if (!info) return { inChart: false, dist: 99, border: null }; // whole family folds
  var inChart = compiled.chart[label] !== undefined;
  var best = 99;
  info.segments.forEach(function (seg) {
    var hiS = familyStep(seg.hi), loS = familyStep(seg.lo);
    if (step <= hiS && step >= loS) {
      best = Math.min(best, Math.min(hiS - step, step - loS)); // inside: distance to nearest edge
    } else {
      var d = step > hiS ? step - hiS : loS - step;
      best = Math.min(best, d);
    }
  });
  return { inChart: inChart, dist: best, border: info.border };
}

/* ---------- hand nature (the WHY vocabulary) ---------- */
function handNature(label) {
  var r = handRank(label);
  var hi = RANKS.indexOf(label[0]), lo = label.length > 2 ? RANKS.indexOf(label[1]) : hi;
  var suited = label[2] === 's';
  var pair = label.length === 2;
  var gap = hi - lo;
  var notes = [];
  if (pair) {
    if (hi >= 10) notes.push('premium pair — pure value everywhere');
    else if (hi >= 7) notes.push('strong pair: usually value, hates heavy action');
    else notes.push('small pair: set-mining and showdown value — wants cheap flops or fold equity');
  } else {
    if (label === 'AKs' || label === 'AKo' || label === 'AQs') notes.push('premium big-card hand: dominates other broadways, blocks AA/KK');
    if (hi === 12 && suited && lo <= 3) notes.push('suited wheel ace: classic 3-bet/jam bluff candidate — blocks AA/AK, makes the nut flush and wheel straights, too weak to call');
    else if (hi === 12 && suited) notes.push('suited ace: nut-flush potential plus an ace blocker');
    else if (hi === 12) notes.push('offsuit ace: blocker value but kicker trouble — playability is poor');
    if (hi !== 12 && hi >= 9 && lo >= 8) notes.push(suited ? 'suited broadway: strong top pairs plus straight/flush equity' : 'offsuit broadway: makes good pairs but is dominated by tighter ranges — position sensitive');
    if (gap === 1 && lo >= 2 && hi <= 11 && suited) notes.push('suited connector: straights, flushes and board coverage — playability over raw strength');
    if (gap === 2 && suited && hi <= 11) notes.push('suited gapper: sneaky straights, decent playability');
    if (!suited && r > 95) notes.push('weak offsuit hand: no flush, poor straights, kicker problems — chart fodder for a reason');
  }
  if (suited && !pair) notes.push('suitedness adds roughly 2-3% raw equity but much more playability (nut potential, semi-bluffs)');
  return { rank: r, percentile: Math.round(100 * (1 - r / 168)), notes: notes };
}

/* ---------- the explanation builder ---------- */
function explainAnswer(chartId, label, userAnswer, accepted) {
  var compiled = COMPILED_CHARTS[chartId];
  var act = compiled.chart[label]; // undefined | action | 'mixed'
  var nature = handNature(label);
  var bd = borderDistance(chartId, label);
  var correct = accepted.indexOf(userAnswer) >= 0;
  var aggressive = GROUP_ANSWERS[compiled.spec.group][GROUP_ANSWERS[compiled.spec.group].length - 1];

  var parts = [];
  // 1) role line
  if (act === undefined) {
    parts.push(label + ' is a fold here (top ' + nature.percentile + '% hand, but this spot demands more).');
  } else if (act === 'mixed') {
    var tgt = compiled.extraMixed[label];
    parts.push(label + ' is a mixed-frequency hand' + (tgt ? ' (sometimes ' + ACTION_META[tgt].label.toLowerCase() + ', sometimes fold)' : '') + ' — the EVs are nearly identical, which is exactly why solvers split it.');
  } else {
    parts.push(label + ' is a ' + ACTION_META[act].label.toUpperCase() + ' (top ' + nature.percentile + '% of starting hands).');
  }
  // 2) why (hand nature) — pick the most relevant note
  if (nature.notes.length) parts.push(nature.notes[0] + '.');
  // 3) border context
  if (bd.border) {
    if (bd.inChart && bd.dist === 0 && act !== 'mixed') {
      parts.push('Border alert: this is the WEAKEST ' + famName(label) + ' that continues here — memorize it as the cut line.');
    } else if (!bd.inChart && bd.dist <= 1) {
      parts.push('Just below the cut: the border for ' + famName(label) + ' is ' + bd.border + '. One notch short.');
    } else if (!bd.inChart && bd.dist <= 3) {
      parts.push('The ' + famName(label) + ' border here is ' + bd.border + ' — this one is ' + bd.dist + ' steps below it.');
    }
  } else if (act === undefined) {
    parts.push('No ' + famName(label) + ' continue in this spot at all.');
  }
  // 4) chart-specific note
  if (compiled.spec.note && !correct) parts.push(compiled.spec.note);

  return {
    correct: correct,
    severity: correct ? null : mistakeSeverity(chartId, label, userAnswer, aggressive),
    text: parts.join(' ')
  };
}
function famName(label) { return FAMILY_NAMES[familyOf(label)] || 'these hands'; }

/* ---------- mistake severity ----------
   'close'   — border-zone or mixed hand: tiny EV loss
   'mistake' — clearly wrong side of the line
   'blunder' — folding a monster / raising junk                       */
function mistakeSeverity(chartId, label, userAnswer, aggressive) {
  var compiled = COMPILED_CHARTS[chartId];
  var act = compiled.chart[label];
  var r = handRank(label);
  var bd = borderDistance(chartId, label);
  // folded a premium / played absolute junk
  if (act && act !== 'mixed' && userAnswer === 'fold' && r <= 12) return 'blunder';
  if (act === undefined && r >= 130 && userAnswer !== 'fold') return 'blunder';
  if (act === 'mixed') return 'close';
  if (bd.dist <= 1) return 'close';
  if (bd.dist <= 3) return 'mistake';
  return 'blunder';
}
var SEVERITY_META = {
  close:   { label: 'Close call', credit: 0.5, cls: 'sev-close',
    blurb: 'Near-zero EV difference — do not sweat these.' },
  mistake: { label: 'Mistake', credit: 0, cls: 'sev-mistake',
    blurb: 'Clearly the wrong side of the line. Worth a chart look.' },
  blunder: { label: 'Blunder', credit: 0, cls: 'sev-blunder',
    blurb: 'Big EV punt — these are the ones that cost real money.' }
};

/* ---------- border-focused drill sampling ----------
   "Interesting" labels for a chart: every in-chart segment edge, one step
   outside each edge, and all mixed hands. That's where learning lives.   */
var _interestCache = {};
function interestingLabels(chartId) {
  if (_interestCache[chartId]) return _interestCache[chartId];
  var compiled = COMPILED_CHARTS[chartId];
  var set = {};
  bordersFor(chartId).forEach(function (b) {
    b.segments.forEach(function (seg) {
      [seg.hi, seg.lo].forEach(function (edge) { set[edge] = true; });
      // one step outside each edge
      var fam = b.family;
      [familyStep(seg.hi) + 1, familyStep(seg.lo) - 1].forEach(function (st) {
        if (st < 0 || st > 12) return;
        var l = labelFromFamilyStep(fam, st);
        if (l && COMPILED_CHARTS[chartId].chart[l] === undefined) set[l] = true;
      });
    });
  });
  for (var label in compiled.chart) if (compiled.chart[label] === 'mixed') set[label] = true;
  var out = Object.keys(set);
  _interestCache[chartId] = out;
  return out;
}
function labelFromFamilyStep(fam, step) {
  if (fam === 'pairs') return RANKS[step] + RANKS[step];
  var hi = fam[0], sfx = fam[1];
  var hiIdx = RANKS.indexOf(hi);
  if (step >= hiIdx) return null;
  return hi + RANKS[step] + sfx;
}
/* pick a concrete combo for a label */
function comboForLabel(label) {
  var combos = classToCombos(label, []);
  return combos[randInt(combos.length)];
}

if (typeof module !== 'undefined') {
  module.exports = {
    PREFLOP_RANK: PREFLOP_RANK, handRank: handRank, familyOf: familyOf,
    bordersFor: bordersFor, borderSummary: borderSummary, borderDistance: borderDistance,
    handNature: handNature, explainAnswer: explainAnswer, mistakeSeverity: mistakeSeverity,
    SEVERITY_META: SEVERITY_META, interestingLabels: interestingLabels,
    labelFromFamilyStep: labelFromFamilyStep, comboForLabel: comboForLabel
  };
}
